spring:
  application:
    name: gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true
      routes:
        - id: context-path-api
          uri: lb://CONTEXT-PATH-API
          predicates:
            - Path=/context-path-api/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api



eureka:
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://vn:8761/eureka/,http://vn:8762/eureka/
#  instance:
#    # 设置自定义的外网地址，防止获取到不能访问的内网ip
#    prefer-ip-address: true
#    ip-address: vn
server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: debug