eureka:
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://vn:8761/eureka/,http://vn:8762/eureka/
  instance:
    # 设置自定义的外网地址，防止获取到不能访问的内网ip
    prefer-ip-address: true
    ip-address: vn
spring:
  application:
    name: context-path-api
  redis:
    host: ameng
    database: 0
    password: springcloudr
  session:
    store-type: redis


server:
  port: 8080
  servlet:
    session:
      cookie:
        path: /
    context-path: /api
